### PR TITLE
Handle the non-integer return of __index__

### LINKED ISSUE #96: Handle the return of non-integer value in __index__ function
An error should occur when returning a non-integer value from __index__.

### Expected result (cpython)
```python
>>> class C:
...     def __index__(self):
...         return 'a'
... 
>>> c = C()
>>> a = [1, 2 ,4]
>>> a[c]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __index__ returned non-int (type str)
```

### Actual result (gpython)
```python
>>> class C:
...     def __index__(self):
...         return 'a'
... 
>>> c = C()
>>> a = [1, 2, 4]
>>> a[c]
1
```

### PR DESCRIPTION
**Pull request by HyeockJinKim**
Generate TypeError when __index__ return non-integer value

Fixes #96

### CODE REVIEW

**Comment by HyeockJinKim** [comment]
@corona10 
Can I get a review?

**Comment by tim-st** [comment]
Does this also affect the `list` type?
CPython supports:
```python
>>> l = [1,2]
>>> class C:
...   def __index__(self):
...     return 1
...
>>> l[C()]
2
```
If your change has an influence on this, you could add a test for list, too.

**Comment by HyeockJinKim** [comment]
@tim-st 
This fix affects strings, tuples, and lists. 
So I added test code for each one. Would you like to review it again?

**Comment by tim-st** [comment]
@HyeockJinKim Looks good, I think it should work now!

**Comment by ncw** [comment]
That looks great now - thank you :-)

**Pull request merged**
