### PR TITLE
parser: Update from go tool yacc into goyacc

### PR DESCRIPTION
**Pull request by corona10**
Since Go 1.8 removed the go tool yacc command,
we should update it to use goyacc

reference: https://beta.golang.org/doc/go1.8#tool_yacc

### CODE REVIEW

**Comment by corona10** [comment]
@ncw @sbinet
I notice that the code coverage metric is not exact. 
I checked that the block which said "no-cover" is already covered on the unit test.

**Comment by sbinet** [comment]
I am on a train + mobile, so I can't easily check... But is the piece of code you say should be tested, is tested within the same package? (There's probably a way to treat a whole repo like a single code-coverage unit so that parts of pkgA that are tested from pkgB still are counted as tested. But I haven't found it.)

**Comment by corona10** [comment]
@sbinet 
Yes, they are on the same package "parser".

**Comment by ncw** [comment]
I think that looks fine to me.  I had a quick look through the auto generated code and it looks like it has just been tidied up.  That may explain the code coverage oddities also since the line count of the generated code has increased.

**Pull request merged**
