### PR TITLE
Improve some things around how errors are reported when parsing a file

### PR DESCRIPTION
**Pull request by Tatskaari**
Given the malformed input "/Users/jpoole/gpython/test.py":
```
def foo(name : str):
    return name

foo(


foo(name = "test"))

foo(

```

Before:
```
Exception &py.Exception{Base:(*py.Type)(0xc00012dc20), Args:py.Tuple{"invalid syntax"}, Traceback:py.Object(nil), Context:py.Object(nil), Cause:py.Object(nil), SuppressContext:false, Dict:py.StringDict{"filename":"<string>", "line":"", "lineno":10, "offset":0}}
-- No traceback available --
2022/04/10 18:31:19 
  File "<string>", line 10, offset 0
    

SyntaxError: 'invalid syntax'
```

After 
```
Exception 
  File "/Users/jpoole/gpython/test.py", line 10, offset 0
    

SyntaxError: 'unexpected EOF while parsing'
-- No traceback available --

```

### CODE REVIEW

**Review by sbinet — COMMENTED** [review]
apologies for dropping the ball.

LGTM, modulo some tests that need to be fixed.

thanks for the PR.

**Comment by Tatskaari** [comment]
> apologies for dropping the ball.
> 
> LGTM, modulo some tests that need to be fixed.
> 
> thanks for the PR.

Nice! Fixed the tests up. They pass locally now.

**Review by sbinet — APPROVED** [review]
LGTM.

thanks for sticking with us.

could you send another PR against [go-python/license](https://github.com/go-python/license) adding yourself to the `AUTHORS` and/or `CONTRIBUTORS` file(s) ?

then I'll merge this one in.

thanks again.

**Comment by sbinet** [comment]
there's one remaining error, though:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: "name 'aksfjakf' is not defined"
--- FAIL: TestREPL (0.00s)
    repl_test.go:32: compileError: Output wrong, want "Compile error: \n  File \"<string>\", line 1, offset 2\n    if\n\n\nSyntaxError: 'invalid syntax'" got "Compile error: \n  File \"<stdin>\", line 1, offset 2\n    if\n\n\nSyntaxError: 'invalid syntax'"
FAIL
FAIL	github.com/go-python/gpython/repl	0.003s
```

**Comment by sbinet** [comment]
needs https://github.com/go-python/license/pull/17

**Comment by sbinet** [comment]
I took the liberty of fixing the last remaining error and pushing my changes, so I could merge this PR in :)

thanks a lot.

**Review by sbinet — APPROVED** [review]
LGTM

**Comment by Tatskaari** [comment]
> I took the liberty of fixing the last remaining error and pushing my changes, so I could merge this PR in :)
> 
> thanks a lot.

Oh so sorry! I got distracted and forgot to get back to this one. Thanks for that :)

**Comment by sbinet** [comment]
no worries :)
(it'd be great to have python-3.x grammar compatibility (where x>4) :P)

**Pull request merged**
