### PR TITLE
add lower() and upper for py str feat:(#232)

### PR DESCRIPTION
**Pull request by wdq112**
add lower() and upper for py str

Updates #232

### CODE REVIEW

**Review by sbinet — APPROVED** [review]
LGTM.

thanks for the PR.

could you send another PR against [go-python/license](https://github.com/go-python/license) adding yourself to the `AUTHORS` and/or `CONTRIBUTORS` file(s) ?
then I'll merge this one in.

thanks again.

**Comment by sbinet** [comment]
perhaps also add a test for `upper` and `lower` in `py/tests/string.py`, after:
https://github.com/go-python/gpython/blob/main/py/tests/string.py#L889...L898

(to appease the testing gods)

**Comment by sbinet** [comment]
needs https://github.com/go-python/license/pull/22

**Comment by sbinet** [comment]
Thanks a lot for this PR.

do you want to give the last leg of #232 (`str.join`) a try ? :}

**Comment by wdq112** [comment]
I'll try it when I have time.

**Pull request merged**
