### PR TITLE
builtin,vm: add implementation for builtin hex function

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
does anybody understand why _e.g._ `builtin_isinstance` and `builtin_hex` are marked as "not covered" while _e.g._ `builtin_sorted` is?

For the life of me, I just don't understand.

**Comment by ncw** [comment]
Codecov seems to do mad things sometimes! Did you force push your branch? I think that makes it worse sometimes.

I wonder if there is a retry button for codecov?

**Comment by sbinet** [comment]
no, I didn't force push. (at least, not for this PR :P)
and actually running `go test -cover` also shows the same behaviour wrt `builtin_hex` and `builtin_sorted`.

**Comment by ncw** [comment]
Very strange. I can't see anything wrong with your code. Might be worth trying with different go versions to see if it is a go bug.

**Comment by sbinet** [comment]
ok. figured it out.

the tests (for `builtin_hex` and `builtin_isinstance`) were in the wrong location (and actually badly written) :)

**Comment by sbinet** [comment]
@ncw PTAL

**Pull request merged**
